"""add agent hierarchy and gmail gemini workflow

Revision ID: 0954606753f5
Revises: 7119cf64f8e8
Create Date: 2026-06-29 17:13:08.282184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0954606753f5'
down_revision: Union[str, Sequence[str], None] = '7119cf64f8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
