"""add delivery workflow state

Revision ID: 0dca5e58bcfb
Revises: ad36fd24c3b2
Create Date: 2026-06-24 01:22:31.637586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dca5e58bcfb'
down_revision: Union[str, Sequence[str], None] = 'ad36fd24c3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_actions',
    sa.Column('action_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=150), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response_type', sa.String(length=50), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_issue_actions_action_id'), 'issue_actions', ['action_id'], unique=False)
    op.create_index(op.f('ix_issue_actions_action_type'), 'issue_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_issue_actions_due_at'), 'issue_actions', ['due_at'], unique=False)
    op.create_index(op.f('ix_issue_actions_issue_id'), 'issue_actions', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issue_actions_status'), 'issue_actions', ['status'], unique=False)
    op.add_column('issues', sa.Column('reference_key', sa.String(length=255), nullable=True))
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('issues', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_issues_reference_key'), 'issues', ['reference_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_reference_key'), table_name='issues')
    op.drop_column('issues', 'resolved_at')
    op.drop_column('issues', 'updated_at')
    op.drop_column('issues', 'reference_key')
    op.drop_index(op.f('ix_issue_actions_status'), table_name='issue_actions')
    op.drop_index(op.f('ix_issue_actions_issue_id'), table_name='issue_actions')
    op.drop_index(op.f('ix_issue_actions_due_at'), table_name='issue_actions')
    op.drop_index(op.f('ix_issue_actions_action_type'), table_name='issue_actions')
    op.drop_index(op.f('ix_issue_actions_action_id'), table_name='issue_actions')
    op.drop_table('issue_actions')
    # ### end Alembic commands ###
