"""add agent hierarchy and email tracking

Revision ID: 7119cf64f8e8
Revises: 0dca5e58bcfb
Create Date: 2026-06-24 14:05:21.611273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7119cf64f8e8'
down_revision: Union[str, Sequence[str], None] = '0dca5e58bcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_actions', sa.Column('external_message_id', sa.String(length=255), nullable=True))
    op.add_column('issue_actions', sa.Column('email_uid', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_issue_actions_email_uid'), 'issue_actions', ['email_uid'], unique=True)
    op.create_index(op.f('ix_issue_actions_external_message_id'), 'issue_actions', ['external_message_id'], unique=True)
    op.add_column('issues', sa.Column('originating_risk_node', sa.String(length=100), nullable=True))
    op.add_column('issues', sa.Column('previous_node', sa.String(length=100), nullable=True))
    op.add_column('issues', sa.Column('follow_up_count', sa.Integer(), nullable=False))
    op.add_column('issues', sa.Column('response_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_issues_originating_risk_node'), 'issues', ['originating_risk_node'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_originating_risk_node'), table_name='issues')
    op.drop_column('issues', 'response_count')
    op.drop_column('issues', 'follow_up_count')
    op.drop_column('issues', 'previous_node')
    op.drop_column('issues', 'originating_risk_node')
    op.drop_index(op.f('ix_issue_actions_external_message_id'), table_name='issue_actions')
    op.drop_index(op.f('ix_issue_actions_email_uid'), table_name='issue_actions')
    op.drop_column('issue_actions', 'email_uid')
    op.drop_column('issue_actions', 'external_message_id')
    # ### end Alembic commands ###
