"""replace old source tables with new source tables

Revision ID: 9026547ab435
Revises: e0c7c1d70d1c
Create Date: 2026-06-16 09:29:02.000245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9026547ab435'
down_revision: Union[str, Sequence[str], None] = 'e0c7c1d70d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    op.execute("DROP TABLE IF EXISTS source_treatment_assignments")
    op.execute("DROP TABLE IF EXISTS source_subject_identity_map")
    op.execute("DROP TABLE IF EXISTS source_subject_visits")
    op.execute("DROP TABLE IF EXISTS source_subjects")
    op.execute("DROP TABLE IF EXISTS source_supply_packages")
    op.execute("DROP TABLE IF EXISTS source_shipments")
    op.execute("DROP TABLE IF EXISTS source_site_system_records")
    op.execute("DROP TABLE IF EXISTS source_trial_sites")
    op.execute("DROP TABLE IF EXISTS source_trial_countries")
    op.execute("DROP TABLE IF EXISTS source_trial_studies")
    op.execute("DROP TABLE IF EXISTS carrier_events")
    op.execute("DROP TABLE IF EXISTS site_receipts")
    op.execute("DROP TABLE IF EXISTS irt_inventory")
    op.execute("DROP TABLE IF EXISTS sap_shipments")
    op.execute("DROP TABLE IF EXISTS sites")

    op.execute("SET FOREIGN_KEY_CHECKS = 1")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('shipment_code', sa.String(length=50), nullable=False),
    sa.Column('origin_location', sa.String(length=100), nullable=True),
    sa.Column('destination_site_code', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('logistics_status', sa.String(length=50), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('site_received_at', sa.DateTime(), nullable=True),
    sa.Column('shipment_type', sa.String(length=50), nullable=True),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_code', sa.String(length=100), nullable=True),
    sa.Column('product_label', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_study_site', 'source_shipments', ['study_code', 'destination_site_code'], unique=False)
    op.create_index(op.f('ix_source_shipments_destination_site_code'), 'source_shipments', ['destination_site_code'], unique=False)
    op.create_index(op.f('ix_source_shipments_id'), 'source_shipments', ['id'], unique=False)
    op.create_index(op.f('ix_source_shipments_shipment_code'), 'source_shipments', ['shipment_code'], unique=True)
    op.create_index(op.f('ix_source_shipments_study_code'), 'source_shipments', ['study_code'], unique=False)
    op.create_table('source_site_system_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('site_system_status', sa.String(length=50), nullable=False),
    sa.Column('site_display_name', sa.String(length=150), nullable=True),
    sa.Column('principal_investigator_name', sa.String(length=150), nullable=True),
    sa.Column('country_label', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('site_activated_at', sa.DateTime(), nullable=True),
    sa.Column('site_deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('screening_status', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_site_system_study_site', 'source_site_system_records', ['study_code', 'site_code'], unique=False)
    op.create_index(op.f('ix_source_site_system_records_id'), 'source_site_system_records', ['id'], unique=False)
    op.create_index(op.f('ix_source_site_system_records_site_code'), 'source_site_system_records', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_site_system_records_study_code'), 'source_site_system_records', ['study_code'], unique=False)
    op.create_table('source_subject_identity_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('participant_code', sa.String(length=50), nullable=False),
    sa.Column('masked_subject_code', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_subject_identity_map_id'), 'source_subject_identity_map', ['id'], unique=False)
    op.create_index(op.f('ix_source_subject_identity_map_masked_subject_code'), 'source_subject_identity_map', ['masked_subject_code'], unique=True)
    op.create_index(op.f('ix_source_subject_identity_map_participant_code'), 'source_subject_identity_map', ['participant_code'], unique=False)
    op.create_index(op.f('ix_source_subject_identity_map_study_code'), 'source_subject_identity_map', ['study_code'], unique=False)
    op.create_table('source_subject_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('visit_code', sa.String(length=50), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('visit_name', sa.String(length=100), nullable=True),
    sa.Column('visit_at', sa.DateTime(), nullable=False),
    sa.Column('drug_required', sa.Boolean(), nullable=False),
    sa.Column('visit_type', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_subject_visits_id'), 'source_subject_visits', ['id'], unique=False)
    op.create_index(op.f('ix_source_subject_visits_site_code'), 'source_subject_visits', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_subject_visits_study_code'), 'source_subject_visits', ['study_code'], unique=False)
    op.create_index(op.f('ix_source_subject_visits_subject_code'), 'source_subject_visits', ['subject_code'], unique=False)
    op.create_index(op.f('ix_source_subject_visits_visit_code'), 'source_subject_visits', ['visit_code'], unique=True)
    op.create_table('source_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('randomization_code', sa.String(length=50), nullable=True),
    sa.Column('subject_status', sa.String(length=50), nullable=False),
    sa.Column('consent_status', sa.String(length=50), nullable=True),
    sa.Column('country_label', sa.String(length=100), nullable=True),
    sa.Column('next_visit_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_subjects_id'), 'source_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_source_subjects_site_code'), 'source_subjects', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_subjects_study_code'), 'source_subjects', ['study_code'], unique=False)
    op.create_index(op.f('ix_source_subjects_subject_code'), 'source_subjects', ['subject_code'], unique=True)
    op.create_table('source_supply_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('kit_code', sa.String(length=50), nullable=False),
    sa.Column('kit_status', sa.String(length=50), nullable=False),
    sa.Column('expiration_at', sa.DateTime(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('site_code', sa.String(length=50), nullable=True),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('visit_code', sa.String(length=50), nullable=True),
    sa.Column('shipment_code', sa.String(length=50), nullable=True),
    sa.Column('depot_label', sa.String(length=100), nullable=True),
    sa.Column('product_label', sa.String(length=100), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_from_shipping_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_from_dispensing_at', sa.DateTime(), nullable=True),
    sa.Column('excluded_from_count_at', sa.DateTime(), nullable=True),
    sa.Column('temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_supply_packages_id'), 'source_supply_packages', ['id'], unique=False)
    op.create_index(op.f('ix_source_supply_packages_kit_code'), 'source_supply_packages', ['kit_code'], unique=True)
    op.create_index(op.f('ix_source_supply_packages_shipment_code'), 'source_supply_packages', ['shipment_code'], unique=False)
    op.create_index(op.f('ix_source_supply_packages_site_code'), 'source_supply_packages', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_supply_packages_study_code'), 'source_supply_packages', ['study_code'], unique=False)
    op.create_index(op.f('ix_source_supply_packages_subject_code'), 'source_supply_packages', ['subject_code'], unique=False)
    op.create_index(op.f('ix_source_supply_packages_visit_code'), 'source_supply_packages', ['visit_code'], unique=False)
    op.create_index('ix_supply_package_shipment', 'source_supply_packages', ['shipment_code'], unique=False)
    op.create_index('ix_supply_package_study_site', 'source_supply_packages', ['study_code', 'site_code'], unique=False)
    op.create_table('source_treatment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('visit_code', sa.String(length=50), nullable=True),
    sa.Column('randomization_code', sa.String(length=50), nullable=False),
    sa.Column('treatment_label', sa.String(length=100), nullable=True),
    sa.Column('treatment_code', sa.String(length=50), nullable=True),
    sa.Column('randomized_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_treatment_assignments_id'), 'source_treatment_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_source_treatment_assignments_randomization_code'), 'source_treatment_assignments', ['randomization_code'], unique=True)
    op.create_index(op.f('ix_source_treatment_assignments_site_code'), 'source_treatment_assignments', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_treatment_assignments_study_code'), 'source_treatment_assignments', ['study_code'], unique=False)
    op.create_index(op.f('ix_source_treatment_assignments_subject_code'), 'source_treatment_assignments', ['subject_code'], unique=False)
    op.create_index(op.f('ix_source_treatment_assignments_visit_code'), 'source_treatment_assignments', ['visit_code'], unique=False)
    op.create_table('source_trial_countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('country_label', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('planned_site_total', sa.Integer(), nullable=True),
    sa.Column('active_site_total', sa.Integer(), nullable=True),
    sa.Column('approval_planned_at', sa.DateTime(), nullable=True),
    sa.Column('approval_actual_at', sa.DateTime(), nullable=True),
    sa.Column('country_status', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_trial_countries_id'), 'source_trial_countries', ['id'], unique=False)
    op.create_index(op.f('ix_source_trial_countries_study_code'), 'source_trial_countries', ['study_code'], unique=False)
    op.create_table('source_trial_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('site_status', sa.String(length=50), nullable=False),
    sa.Column('site_activated_at', sa.DateTime(), nullable=True),
    sa.Column('country_label', sa.String(length=100), nullable=True),
    sa.Column('institution_name', sa.String(length=150), nullable=True),
    sa.Column('investigator_name', sa.String(length=150), nullable=True),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('screening_subject_count', sa.Integer(), nullable=True),
    sa.Column('screen_fail_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_trial_sites_id'), 'source_trial_sites', ['id'], unique=False)
    op.create_index(op.f('ix_source_trial_sites_site_code'), 'source_trial_sites', ['site_code'], unique=False)
    op.create_index(op.f('ix_source_trial_sites_study_code'), 'source_trial_sites', ['study_code'], unique=False)
    op.create_index('ix_trial_site_study_site', 'source_trial_sites', ['study_code', 'site_code'], unique=False)
    op.create_table('source_trial_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_code', sa.String(length=50), nullable=False),
    sa.Column('study_status', sa.String(length=50), nullable=False),
    sa.Column('study_manager_name', sa.String(length=100), nullable=True),
    sa.Column('supply_manager_name', sa.String(length=100), nullable=True),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('planned_site_total', sa.Integer(), nullable=True),
    sa.Column('active_site_total', sa.Integer(), nullable=True),
    sa.Column('first_visit_planned_at', sa.DateTime(), nullable=True),
    sa.Column('first_visit_actual_at', sa.DateTime(), nullable=True),
    sa.Column('last_visit_planned_at', sa.DateTime(), nullable=True),
    sa.Column('last_visit_actual_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_trial_studies_id'), 'source_trial_studies', ['id'], unique=False)
    op.create_index(op.f('ix_source_trial_studies_study_code'), 'source_trial_studies', ['study_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('ctms_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('irt_status', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('site_code'), 'sites', ['site_code'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('site_receipts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receipt_status', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['sap_shipments.id'], name=op.f('site_receipts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_site_receipts_id'), 'site_receipts', ['id'], unique=False)
    op.create_table('carrier_events',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carrier_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('proof_of_delivery_available', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['sap_shipments.id'], name=op.f('carrier_events_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_carrier_events_id'), 'carrier_events', ['id'], unique=False)
    op.create_table('sap_shipments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shipment_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('site_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sap_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('planned_delivery_date', mysql.DATETIME(), nullable=True),
    sa.Column('actual_delivery_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('sap_shipments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('shipment_code'), 'sap_shipments', ['shipment_code'], unique=True)
    op.create_index(op.f('ix_sap_shipments_id'), 'sap_shipments', ['id'], unique=False)
    op.create_table('irt_inventory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('available_kits', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('safety_stock_threshold', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('irt_inventory_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_irt_inventory_id'), 'irt_inventory', ['id'], unique=False)
    op.drop_index(op.f('ix_source_trial_studies_study_code'), table_name='source_trial_studies')
    op.drop_index(op.f('ix_source_trial_studies_id'), table_name='source_trial_studies')
    op.drop_table('source_trial_studies')
    op.drop_index('ix_trial_site_study_site', table_name='source_trial_sites')
    op.drop_index(op.f('ix_source_trial_sites_study_code'), table_name='source_trial_sites')
    op.drop_index(op.f('ix_source_trial_sites_site_code'), table_name='source_trial_sites')
    op.drop_index(op.f('ix_source_trial_sites_id'), table_name='source_trial_sites')
    op.drop_table('source_trial_sites')
    op.drop_index(op.f('ix_source_trial_countries_study_code'), table_name='source_trial_countries')
    op.drop_index(op.f('ix_source_trial_countries_id'), table_name='source_trial_countries')
    op.drop_table('source_trial_countries')
    op.drop_index(op.f('ix_source_treatment_assignments_visit_code'), table_name='source_treatment_assignments')
    op.drop_index(op.f('ix_source_treatment_assignments_subject_code'), table_name='source_treatment_assignments')
    op.drop_index(op.f('ix_source_treatment_assignments_study_code'), table_name='source_treatment_assignments')
    op.drop_index(op.f('ix_source_treatment_assignments_site_code'), table_name='source_treatment_assignments')
    op.drop_index(op.f('ix_source_treatment_assignments_randomization_code'), table_name='source_treatment_assignments')
    op.drop_index(op.f('ix_source_treatment_assignments_id'), table_name='source_treatment_assignments')
    op.drop_table('source_treatment_assignments')
    op.drop_index('ix_supply_package_study_site', table_name='source_supply_packages')
    op.drop_index('ix_supply_package_shipment', table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_visit_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_subject_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_study_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_site_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_shipment_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_kit_code'), table_name='source_supply_packages')
    op.drop_index(op.f('ix_source_supply_packages_id'), table_name='source_supply_packages')
    op.drop_table('source_supply_packages')
    op.drop_index(op.f('ix_source_subjects_subject_code'), table_name='source_subjects')
    op.drop_index(op.f('ix_source_subjects_study_code'), table_name='source_subjects')
    op.drop_index(op.f('ix_source_subjects_site_code'), table_name='source_subjects')
    op.drop_index(op.f('ix_source_subjects_id'), table_name='source_subjects')
    op.drop_table('source_subjects')
    op.drop_index(op.f('ix_source_subject_visits_visit_code'), table_name='source_subject_visits')
    op.drop_index(op.f('ix_source_subject_visits_subject_code'), table_name='source_subject_visits')
    op.drop_index(op.f('ix_source_subject_visits_study_code'), table_name='source_subject_visits')
    op.drop_index(op.f('ix_source_subject_visits_site_code'), table_name='source_subject_visits')
    op.drop_index(op.f('ix_source_subject_visits_id'), table_name='source_subject_visits')
    op.drop_table('source_subject_visits')
    op.drop_index(op.f('ix_source_subject_identity_map_study_code'), table_name='source_subject_identity_map')
    op.drop_index(op.f('ix_source_subject_identity_map_participant_code'), table_name='source_subject_identity_map')
    op.drop_index(op.f('ix_source_subject_identity_map_masked_subject_code'), table_name='source_subject_identity_map')
    op.drop_index(op.f('ix_source_subject_identity_map_id'), table_name='source_subject_identity_map')
    op.drop_table('source_subject_identity_map')
    op.drop_index(op.f('ix_source_site_system_records_study_code'), table_name='source_site_system_records')
    op.drop_index(op.f('ix_source_site_system_records_site_code'), table_name='source_site_system_records')
    op.drop_index(op.f('ix_source_site_system_records_id'), table_name='source_site_system_records')
    op.drop_index('ix_site_system_study_site', table_name='source_site_system_records')
    op.drop_table('source_site_system_records')
    op.drop_index(op.f('ix_source_shipments_study_code'), table_name='source_shipments')
    op.drop_index(op.f('ix_source_shipments_shipment_code'), table_name='source_shipments')
    op.drop_index(op.f('ix_source_shipments_id'), table_name='source_shipments')
    op.drop_index(op.f('ix_source_shipments_destination_site_code'), table_name='source_shipments')
    op.drop_index('ix_shipment_study_site', table_name='source_shipments')
    op.drop_table('source_shipments')
    # ### end Alembic commands ###
