"""add agent hierarchy and gmail gemini workflow

Revision ID: 99c5c13f9a6c
Revises: 0954606753f5
Create Date: 2026-06-29 17:16:39.560608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c5c13f9a6c'
down_revision: Union[str, Sequence[str], None] = '0954606753f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
