"""fix

Revision ID: ad36fd24c3b2
Revises: 657fdc1a3532
Create Date: 2026-06-22 23:06:35.247803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad36fd24c3b2'
down_revision: Union[str, Sequence[str], None] = '657fdc1a3532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('issue_id')
    )
    op.create_index(op.f('ix_issues_issue_id'), 'issues', ['issue_id'], unique=False)
    op.create_index(op.f('ix_issues_issue_type'), 'issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_issues_risk_type'), 'issues', ['risk_type'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('studies',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('study_status', sa.String(length=50), nullable=False),
    sa.Column('study_manager_name', sa.String(length=100), nullable=True),
    sa.Column('study_manager_email', sa.String(length=150), nullable=True),
    sa.Column('supply_manager_name', sa.String(length=100), nullable=True),
    sa.Column('supply_manager_email', sa.String(length=150), nullable=True),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('planned_site_total', sa.Integer(), nullable=True),
    sa.Column('active_site_total', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('study_id')
    )
    op.create_index(op.f('ix_studies_study_id'), 'studies', ['study_id'], unique=False)
    op.create_table('countries',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('planned_site_total', sa.Integer(), nullable=True),
    sa.Column('active_site_total', sa.Integer(), nullable=True),
    sa.Column('approval_planned_at', sa.DateTime(), nullable=True),
    sa.Column('approval_actual_at', sa.DateTime(), nullable=True),
    sa.Column('country_status', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'country_id')
    )
    op.create_index(op.f('ix_countries_country_id'), 'countries', ['country_id'], unique=False)
    op.create_index('ix_countries_study_country', 'countries', ['study_id', 'country_id'], unique=False)
    op.create_index(op.f('ix_countries_study_id'), 'countries', ['study_id'], unique=False)
    op.create_table('issue_evidence',
    sa.Column('evidence_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.issue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_issue_evidence_evidence_id'), 'issue_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_issue_evidence_issue_id'), 'issue_evidence', ['issue_id'], unique=False)
    op.create_table('sites',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('planned_activation_date', sa.DateTime(), nullable=True),
    sa.Column('actual_activation_date', sa.DateTime(), nullable=True),
    sa.Column('site_status', sa.String(length=50), nullable=False),
    sa.Column('institution_name', sa.String(length=150), nullable=True),
    sa.Column('investigator_name', sa.String(length=150), nullable=True),
    sa.Column('investigator_email', sa.String(length=150), nullable=True),
    sa.Column('planned_subject_total', sa.Integer(), nullable=True),
    sa.Column('actual_subject_total', sa.Integer(), nullable=True),
    sa.Column('planned_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('actual_enrollment_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'country_id'], ['countries.study_id', 'countries.country_id'], name='fk_sites_country'),
    sa.PrimaryKeyConstraint('study_id', 'site_id')
    )
    op.create_index(op.f('ix_sites_country_id'), 'sites', ['country_id'], unique=False)
    op.create_index(op.f('ix_sites_site_id'), 'sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_sites_study_id'), 'sites', ['study_id'], unique=False)
    op.create_index('ix_sites_study_site', 'sites', ['study_id', 'site_id'], unique=False)
    op.create_table('irt_sites',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('site_system_status', sa.String(length=50), nullable=False),
    sa.Column('site_display_name', sa.String(length=150), nullable=True),
    sa.Column('investigator_name', sa.String(length=150), nullable=True),
    sa.Column('investigator_email', sa.String(length=150), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('site_activated_at', sa.DateTime(), nullable=True),
    sa.Column('site_deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_irt_sites_site', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'site_id')
    )
    op.create_index(op.f('ix_irt_sites_site_id'), 'irt_sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_irt_sites_study_id'), 'irt_sites', ['study_id'], unique=False)
    op.create_index('ix_irt_sites_study_site', 'irt_sites', ['study_id', 'site_id'], unique=False)
    op.create_table('shipments',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('origin_location', sa.String(length=100), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('logistics_status', sa.String(length=50), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('carrier_name', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('product_label', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_shipments_site', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'shipment_id')
    )
    op.create_index(op.f('ix_shipments_shipment_id'), 'shipments', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipments_site_id'), 'shipments', ['site_id'], unique=False)
    op.create_index(op.f('ix_shipments_study_id'), 'shipments', ['study_id'], unique=False)
    op.create_index('ix_shipments_study_site', 'shipments', ['study_id', 'site_id'], unique=False)
    op.create_table('subjects',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('randomization_id', sa.String(length=50), nullable=True),
    sa.Column('subject_status', sa.String(length=50), nullable=False),
    sa.Column('next_visit_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_subjects_site', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'subject_id')
    )
    op.create_index(op.f('ix_subjects_randomization_id'), 'subjects', ['randomization_id'], unique=False)
    op.create_index(op.f('ix_subjects_site_id'), 'subjects', ['site_id'], unique=False)
    op.create_index(op.f('ix_subjects_study_id'), 'subjects', ['study_id'], unique=False)
    op.create_index('ix_subjects_study_site', 'subjects', ['study_id', 'site_id'], unique=False)
    op.create_index(op.f('ix_subjects_subject_id'), 'subjects', ['subject_id'], unique=False)
    op.create_table('kits',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('kit_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('kit_status', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=True),
    sa.Column('expiration_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('dispensed_at', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.String(length=50), nullable=True),
    sa.Column('depot_label', sa.String(length=100), nullable=True),
    sa.Column('product_label', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'shipment_id'], ['shipments.study_id', 'shipments.shipment_id'], name='fk_kits_shipment'),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_kits_site'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.study_id'], name='fk_kits_study', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'kit_id')
    )
    op.create_index(op.f('ix_kits_kit_id'), 'kits', ['kit_id'], unique=False)
    op.create_index(op.f('ix_kits_shipment_id'), 'kits', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_kits_site_id'), 'kits', ['site_id'], unique=False)
    op.create_index(op.f('ix_kits_study_id'), 'kits', ['study_id'], unique=False)
    op.create_index('ix_kits_study_shipment', 'kits', ['study_id', 'shipment_id'], unique=False)
    op.create_index('ix_kits_study_site', 'kits', ['study_id', 'site_id'], unique=False)
    op.create_table('randomization',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('randomization_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('visit_id', sa.String(length=50), nullable=True),
    sa.Column('treatment_label', sa.String(length=100), nullable=True),
    sa.Column('treatment_id', sa.String(length=50), nullable=True),
    sa.Column('randomized_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_randomization_site', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id', 'subject_id'], ['subjects.study_id', 'subjects.subject_id'], name='fk_randomization_subject', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'randomization_id')
    )
    op.create_index(op.f('ix_randomization_randomization_id'), 'randomization', ['randomization_id'], unique=False)
    op.create_index(op.f('ix_randomization_site_id'), 'randomization', ['site_id'], unique=False)
    op.create_index(op.f('ix_randomization_study_id'), 'randomization', ['study_id'], unique=False)
    op.create_index('ix_randomization_study_subject', 'randomization', ['study_id', 'subject_id'], unique=False)
    op.create_index(op.f('ix_randomization_subject_id'), 'randomization', ['subject_id'], unique=False)
    op.create_index(op.f('ix_randomization_visit_id'), 'randomization', ['visit_id'], unique=False)
    op.create_table('visits',
    sa.Column('study_id', sa.String(length=50), nullable=False),
    sa.Column('visit_id', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('visit_at', sa.DateTime(), nullable=False),
    sa.Column('drug_required', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['study_id', 'site_id'], ['sites.study_id', 'sites.site_id'], name='fk_visits_site', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_id', 'subject_id'], ['subjects.study_id', 'subjects.subject_id'], name='fk_visits_subject', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'visit_id')
    )
    op.create_index(op.f('ix_visits_site_id'), 'visits', ['site_id'], unique=False)
    op.create_index(op.f('ix_visits_study_id'), 'visits', ['study_id'], unique=False)
    op.create_index('ix_visits_study_subject', 'visits', ['study_id', 'subject_id'], unique=False)
    op.create_index(op.f('ix_visits_subject_id'), 'visits', ['subject_id'], unique=False)
    op.create_index(op.f('ix_visits_visit_id'), 'visits', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_subject_id'), table_name='visits')
    op.drop_index('ix_visits_study_subject', table_name='visits')
    op.drop_index(op.f('ix_visits_study_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_site_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_randomization_visit_id'), table_name='randomization')
    op.drop_index(op.f('ix_randomization_subject_id'), table_name='randomization')
    op.drop_index('ix_randomization_study_subject', table_name='randomization')
    op.drop_index(op.f('ix_randomization_study_id'), table_name='randomization')
    op.drop_index(op.f('ix_randomization_site_id'), table_name='randomization')
    op.drop_index(op.f('ix_randomization_randomization_id'), table_name='randomization')
    op.drop_table('randomization')
    op.drop_index('ix_kits_study_site', table_name='kits')
    op.drop_index('ix_kits_study_shipment', table_name='kits')
    op.drop_index(op.f('ix_kits_study_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_site_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_shipment_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_kit_id'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_subjects_subject_id'), table_name='subjects')
    op.drop_index('ix_subjects_study_site', table_name='subjects')
    op.drop_index(op.f('ix_subjects_study_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_site_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_randomization_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index('ix_shipments_study_site', table_name='shipments')
    op.drop_index(op.f('ix_shipments_study_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_site_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_irt_sites_study_site', table_name='irt_sites')
    op.drop_index(op.f('ix_irt_sites_study_id'), table_name='irt_sites')
    op.drop_index(op.f('ix_irt_sites_site_id'), table_name='irt_sites')
    op.drop_table('irt_sites')
    op.drop_index('ix_sites_study_site', table_name='sites')
    op.drop_index(op.f('ix_sites_study_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_site_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_country_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_issue_evidence_issue_id'), table_name='issue_evidence')
    op.drop_index(op.f('ix_issue_evidence_evidence_id'), table_name='issue_evidence')
    op.drop_table('issue_evidence')
    op.drop_index(op.f('ix_countries_study_id'), table_name='countries')
    op.drop_index('ix_countries_study_country', table_name='countries')
    op.drop_index(op.f('ix_countries_country_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_studies_study_id'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_risk_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
