"""create initial tables

Revision ID: e0c7c1d70d1c
Revises: 
Create Date: 2026-06-15 11:09:12.179981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c7c1d70d1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=100), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_evidence_id'), 'issue_evidence', ['id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('ctms_status', sa.String(length=50), nullable=False),
    sa.Column('irt_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_code')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('irt_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('available_kits', sa.Integer(), nullable=False),
    sa.Column('safety_stock_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_irt_inventory_id'), 'irt_inventory', ['id'], unique=False)
    op.create_table('sap_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_code', sa.String(length=50), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('sap_status', sa.String(length=50), nullable=False),
    sa.Column('planned_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_code')
    )
    op.create_index(op.f('ix_sap_shipments_id'), 'sap_shipments', ['id'], unique=False)
    op.create_table('carrier_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('carrier_status', sa.String(length=50), nullable=False),
    sa.Column('proof_of_delivery_available', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['sap_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_events_id'), 'carrier_events', ['id'], unique=False)
    op.create_table('site_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('receipt_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['sap_shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_receipts_id'), 'site_receipts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_receipts_id'), table_name='site_receipts')
    op.drop_table('site_receipts')
    op.drop_index(op.f('ix_carrier_events_id'), table_name='carrier_events')
    op.drop_table('carrier_events')
    op.drop_index(op.f('ix_sap_shipments_id'), table_name='sap_shipments')
    op.drop_table('sap_shipments')
    op.drop_index(op.f('ix_irt_inventory_id'), table_name='irt_inventory')
    op.drop_table('irt_inventory')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_issue_evidence_id'), table_name='issue_evidence')
    op.drop_table('issue_evidence')
    # ### end Alembic commands ###
